### ISSUE TITLE
Pre/Post rename checklist

### ISSUE THREAD

**Issue by renefritze** [dune-gdt/dune-merged#11]
Before we rename this repo to `dune-gdt`:

- [ ] remove dummy tags (all which have no matching pypi release?)
- [ ] #15

After we have renamed the repo:
- [ ] update README
- [ ] ensure correct license + URL header

@ftschindler please edit if you think of something else

**Comment by ftschindler** [comment]
will do

**Comment by renefritze** [comment]
Made this issue into a project instead :open_mouth:

**Comment by renefritze** [comment]
https://github.com/orgs/dune-gdt/projects/1/views/1
