### ISSUE TITLE
move pybind11 to deps/

### ISSUE THREAD

**Issue by ftschindler** [dune-gdt/dune-merged#15]
Or am I missing something, @renefritze?

**Comment by renefritze** [comment]
We could move that sure. But it's directly referenced in our cmake now, right? It's not a sep dune module.

**Comment by ftschindler** [comment]
Well, I thought of `deps/` as : everything that is not dune-gdt that we need/want to ship as a dependency. As such, pybind11 seemed a good fit like the rest.
